### ISSUE TITLE
All data from a public release is null

### ISSUE THREAD

**Issue by T145** [KevinRohn/github-full-release-data#3]
Reference provided [here](https://github.com/T145/black-mirror/runs/6389091569?check_suite_focus=true#step%3A9%3A89=).

Is there something wrong with the action or its configuration?

**Comment by kirillmorozov** [comment]
@T145, I may have solved this issue in #4.

**Comment by T145** [comment]
Yes it's been fixed! Thank you.

**Comment by KevinRohn** [comment]
Sorry for the late reply! There is a new version https://github.com/KevinRohn/github-full-release-data/releases/tag/v2.0.1 with the included merge of the pr https://github.com/KevinRohn/github-full-release-data/pull/4
