### ISSUE TITLE
`v2` tag

### ISSUE THREAD

**Issue by kirillmorozov** [KevinRohn/github-full-release-data#5]
@KevinRohn, can you make a `v2` tag in this repository which will point to the latest `v2` version of this action so we can use it in our workflows like this:
```yml
  - name: Get Release data of private repository
    uses: KevinRohn/github-full-release-data@v2
```
And there won't be any need to update all workflows when a non-breaking change is introduced.

**Comment by KevinRohn** [comment]
Ok, I will have a look at it. I will let you know, when it`s done!

**Comment by KevinRohn** [comment]
@kirillmorozov done.
